[package]
name = "aoc2020"
version = "0.1.0"
authors = ["bheklilr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1"
lazy_static = "1.4"
petgraph = "0.5"
rayon = "1.5.0"
meval = "0.2"